---

- name: Boot all the resources for the Slurm cluster in an OpenStack cloud
  hosts: localhost

  tasks:

    - name: Query os project subnet info (filtering by project) | Default
      os_subnets_info:
        filters:
          project_id: "{{ ansible_env.OS_PROJECT_ID }}"
      register: _output

    # this task is only executed if openstack_subnets[] is NOT an empty list
    - name: Set var _os_project_net_info with the os project net details | Default
      set_fact:
        _os_project_subnet_info: "{{ _output.openstack_subnets[0] }}"
      when: _output.openstack_subnets | length > 0

    # if filtering by project didn't work we try without any filter
    - name: Query os project net info (without filtering by project)
      block:

        - name: Query os project net info (without any filter)
          os_subnets_info:
          register: _output

        # - debug:
        #     var: _output.openstack_subnets

        - name: Set var _os_net_info with the os project IPV4 net details
          set_fact:
            _os_project_subnet_info: "{{ item }}"
          loop: "{{ _output.openstack_subnets }}"
          when: item.ip_version|int == 4

      when: _os_project_subnet_info is not defined

    - debug:
        var: _os_project_subnet_info

    # - debug:
    #     var: _output.openstack_subnets

    # - debug:
    #     var: _os_project_subnet_info.cidr

    # - name: Add a test security group allowing incoming traffic from the tenant subnet
    #   os_security_group_rule:
    #     security_group: "test_security_group_to_delete"
    #     direction: ingress
    #     remote_ip_prefix: "{{ _os_project_subnet_cidr }}"
