---

## these are the tasks we will run in every machine in the cluster

- name: Prepare the machine to be managed with ansible
  import_role:
    name: robertdebock.bootstrap

- name: Install core deps
  import_role:
    name: robertdebock.core_dependencies

- name: set hostname as defined in inventory
  hostname:
    name: "{{ hostvars[inventory_hostname].inventory_hostname }}"

- name: Make sure that cron is installed and enabled
  import_role:
    name: robertdebock.cron

- name: Configure NTP time
  import_role:
    name: robertdebock.ntp

- name: Customization for every CentOS/RedHat machine
  block:

    - name: RedHat | Install epel repository
      package:
        name: epel-release
        state: installed
      tags: epel

    - name: RedHat | Make sure SElinux is disabled
      import_role:
        name: pescobar.selinux_disable
      vars:
        selinux_reboot: true
      tags: selinux

    - name: RedHat | Install and then stop/disable firewalld
      block:

          - name: RedHat | Install firewalld
            package:
              name: firewalld
              state: installed

          - name: RedHat | Stop and disable and firewalld
            service:
              name: firewalld
              state: stopped
              enabled: no

  when: ansible_os_family == 'RedHat'

- name: Customization for every machine in the slurm cluster
  block:

    - name: SLURM | Deploy a custom /etc/hosts
      template:
        dest: /etc/hosts
        src: hosts.j2
      tags: etc_hosts

    - name: SLURM | Add OpenHPC repositories
      yum:
        name: "{{ slurm_cluster_ohpc_repos_url }}"
        state: installed

    - name: SLURM | Install some basic packages
      package:
        name: "{{ slurm_cluster_packages_to_install }}"
        state: installed

    - name: SLURM | Upgrade all packages and reboot if a new kernel was installed
      import_role:
        name: pescobar.upgrade_all_packages
      when: slurm_cluster_upgrade_all_packages
      tags: upgrade

  when: "'slurm_cluster_all' in group_names"

