---

## these are the tasks we will run in every slurm machine (master and workers)

- name: Add OpenHPC repositories
  yum:
    name: "{{ bm_ohpc_repos_url }}"
    state: installed

- name: Install OpenHPC runtime Slurm packages
  yum:
    name:
      - "slurm-ohpc"
      - "munge-ohpc"
      - "slurm-example-configs-ohpc"
    state: present

- name: Ensure the Slurm spool directory exists
  file:
    path: /var/spool/slurm
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Ensure the Slurm log directory exists
  file:
    path: /var/log/slurm
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Generate a Munge key for the cluster (in slurm master machine)
  command: "dd if=/dev/urandom of=/etc/munge/munge.key bs=1 count=1024"
  args:
    creates: "/etc/munge/munge.key"
  when: "'slurm_master_group' in group_names"

- name: Retrieve Munge key from Slurm master host
  slurp:
    src: "/etc/munge/munge.key"
  register: _slurm_munge_key
  when: "'slurm_master_group' in group_names"

- name: Write Munge key to every machine
  copy:
    content: "{{ hostvars[groups.slurm_master_group[0]]['_slurm_munge_key']['content'] | b64decode }}"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400
  notify:
    - Restart Munge service

- name: Start and enable munge service
  service:
    name: munge
    state: started
    enabled: true

- name: Apply customised SLURM configuration
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart SLURM service
  tags: slurm_config


  handlers:

    - name: Restart Munge service
      service:
        name: munge
        state: restarted
