---

## UPDATE THESE VARS TO ADAPT THEM TO YOUR OPENSTACK CLOUD
local_image: "CentOS 7 (SWITCHengines)"
local_ssh_remote_user: "centos"
local_flavor: "m1.xxlarge"  # 16cpus / 32GB ram / 160GB hd
local_floating_ips_pool: "public"
local_private_network: "private"
local_nodes_count: "2"
local_terraform_project_path: "{{ playbook_dir }}/../terraform/openmp-course-openstack/"
## UPDATE THESE VARS TO ADAPT THEM TO YOUR OPENSTACK CLOUD

## UPDATE VARS BELOW ACCORDING TO YOUR PREFERENCE BUT IT'S NOT MANDATORY FOR INITIAL TESTING ##

# Details for the ssh key we will create in the local machine to access the cloud machines
# We will also create a ssh config file to use the login node as ssh bastion host
local_ssh_key_path: "{{ ansible_env.HOME }}/.ssh/openmp_course_cloud"
local_ssh_key_name: "openmp_course_cloud"  # name used to register the ssh key in openstack

ntp_timezone: Europe/Zurich

# ports accesible from the internet
local_open_ports:
  - port: 22
    source: 0.0.0.0/0
  - port: 3000
    source: 131.152.0.0/16

local_users_default_group: "course"  # this is the default group for all the user accounts
local_users_accounts_to_create: 32   # how many user accounts to create
local_users_password: "$6$rJgMMBkqe$mk20Kv6tlmEl.A7yg0/jtGTIfBYEQBB67PJwkeEk7JUkiwymP7dDkUxxeOQU/tUPHK4VBiiPnlxMvCfWHcelx0"  # openmp_course_2021

cgroup_memory_limit: "4G"
cgroup_to_whom_the_limit_applies: "@{{ local_users_default_group }}"

fail2ban_ignoreips: "127.0.0.1/8 ::1 131.152.0.0/16"
fail2ban_jail_configuration:
  - section: sshd
    option: enabled
    value: "true"

local_upgrade_all_packages: false
local_packages_to_install:
  - vim
  - emacs-nox
  - nano
  - git
  - htop
  - bash-completion
  - singularity
  - screen
  - tmux

# Set this var to "True" to configure the ComputeCanada software stack in every machine
local_enable_compute_canada_software_stack: true

local_teachers_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEFya9i7rLPXOEtdGhHB4nTfjXKNZPfcLwrMTtbJqM/y wandrille.duchemin@unibas.ch"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfdQDNeDOqstuSqPYRzwkdjQRQOs7rf2+Ejb7HAxHkn7my9MW/Yoh/uF/QgEXbJTfCRsty1FOC+m/MOJ22KEjEEbkymIwKQqTTj2DoRchnOMbMo1dU4ohkDS+GBGsB0BhccFzXvmhVfTuPctA5b/agTHyozAV/9yK+vm7CfJPpjxpJUb7yXP+QVBIA653Tve+wB0JCzF4uJhhratuFYdvPSIzWTRGqKJ6jIfJ7GpeoobESOl56isHl+HerVF5ZBdUwEbb9rg/bRORw2Q3KuWGqWyyXOcrAJzg1cHcSAxtpDkAY5a8Tx69nZDvaQ/HQX9O0v24or/o3DwydRpGimpON acavelan@kahos"

local_grafana_admin_password: "grafana009988"
