---

## UPDATE THESE VARS TO ADAPT THEM TO YOUR OPENSTACK CLOUD
slurm_image: "CentOS 7 (SWITCHengines)"
slurm_ssh_remote_user: "centos"
slurm_login_flavor: "m1.small"
slurm_compute_flavor: "m1.small"
slurm_floating_ips_pool: "public"
slurm_private_network: "private"
slurm_compute_nodes_count: "3"
slurm_nfs_server_shared_disk_size: "50"
slurm_terraform_project_path: "{{ playbook_dir }}/../terraform/slurm-cluster-openstack/"
## UPDATE THESE VARS TO ADAPT THEM TO YOUR OPENSTACK CLOUD

## UPDATE VARS BELOW ACCORDING TO YOUR PREFERENCE BUT IT'S NOT MANDATORY FOR INITIAL TESTING ##

# Details for the ssh key we will create in the local machine to access the cloud machines
# We will also create a ssh config file to use the login node as ssh bastion host
slurm_ssh_key_path: "{{ ansible_env.HOME }}/.ssh/slurm_cluster_cloud"
slurm_ssh_key_name: "slurm_cluster_cloud"  # name used to register the ssh key in openstack
slurm_ssh_cfg_path: "{{ ansible_env.HOME }}/.ssh/slurm_cluster_cloud.cfg"

# we will use these vars to configure /etc/exports in the NFS server and mounts in the NFS clients
slurm_nfs_server: slurm-login
slurm_shared_folder: /shared

slurm_ntp_timezone: Europe/Zurich

slurm_login_open_ports:
  - port: 22
    source: 0.0.0.0/0
  - port: 80
    source: 0.0.0.0/0
  - port: 443
    source: 0.0.0.0/0
  - port: 3000
    source: 131.152.0.0/16

# How to configure the mysql database for the slurm accounting daemon
slurm_slurmdbd_mysql_db: "slurm"
slurm_slurmdbd_mysql_password: "Guan1iineN6yaxec"
slurm_slurmdbd_mysql_user: "slurmdbuser"

# This RPM will be installed to provide the OpenHPC repositories. We will install slurm packages from this repo
# Check latest releases in https://openhpc.community/downloads/
slurm_ohpc_repos_url: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"

# Set this variable to "True" in case you want to do a "yum -y update" in every machine
slurm_upgrade_all_packages: false

# list of packages we want in every machine
slurm_packages_to_install:
  - vim
  - emacs-nox
  - nano
  - git
  - htop
  - bash-completion
  - singularity
  - screen
  - tmux

# Details for the local accounts to create in every machine
slurm_users_accounts: 30
# https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
slurm_users_default_password: "$6$ldwSs5IPrUFC$mTJprVShXmBCd.DMYGR0SP31BcUUiReQEErn2s4cN3o91V5du/FnurZF/RU/nPnfrWZ1Sxr1pdjtvH6uG37Ee."  # slurm_cluster

# Set this var to "True" to configure the ComputeCanada software stack in every machine
slurm_enable_compute_canada_software_stack: true

# Define the list of R packages you want to install the login node (to be used in Rstudio)
rstudio_server_extra_r_packages:
  - cluster
  - DESeq2
  - edgeR
  - pheatmap
  - AnnotationHub
  - AnnotationDbi
  - clusterProfiler
  - ReactomePA
  - org.Mm.eg.db
  # - ggplot2
  # - gplots
  # - dplyr
  # - edgeR
  # - QuasR

cgroup_memory_limit: '4G'

slurm_teachers_ssh_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzghWVPGdgvHrtIFv+9xoCDQD4N1ljhV5G0Ga2gyeigqo6ihoXKKUNtmecSaUsZYAPg+wUqCNhBb1oY0pC/MA/bCT4DAN/p+nt7wKc8okOWO5DRX9Asq00JmU9sDo8joKeUyGDl6+FmF6YBzfzwR7mEOyoq3cxim1jaBvuC/JaCE+e1Jdn++Vjz5fHQFuUPKMyXIXlaXLs6D7n2Zq9IfK1eMfCv22d3wm1MOEZSlkYHeyLdfNWVPpMroCyPkImI0gODde3yIaoDu/ETXQxFUHyvFZ7gOnm3/O6rpswB+DYRUlrpNQMZm5Koq7dG9HW4zhN6MMt8c2ZV3TlXxHgCMfJ6G6SNVZ8GaowxW3cGA0Hu55qgP8Vg+0U/o3VFqYJeh60mGILPhJqK+m/GwYWr4Mmi69/ehBX18KTVo7HrKNfUTwPhXg3hRa2KoLvhZrvtrm7gh3bj2Rao+E/WBwH3f9HAxtA8ebFy9Akre+BeF9+VrRbM7ZU1AX34bDfrHIwWx0Klr9MldZRzKvD1S3CUBkhDpy5FUKObVU3Vuz3ZkOqy+JKy8K5u/Q8WraFh5jiE2cmjSmsSGlVbQyHaLY5kS+yzMGWdlZ6mErGCOEfUk9xTd6i9A4Parsxctl0ybaySVn932x3Sc93pq1s7FPWwhA9wk8PqknKl+28ckf0tE3SQw=="

grafana_admin_password: "grafana009988"
