#!/usr/bin/env ansible-playbook
---

- name: Boot the OpenMP course machines on OpenStack using Terraform and create an ansible static inventory
  hosts: localhost
  become: no
  gather_facts: yes


  tasks:

    - name: Create a ssh key
      community.crypto.openssh_keypair:
        path: "{{ local_ssh_key_path }}"
      register: _ssh_key_info

    - name: Register the ssh key in OpenStack
      openstack.cloud.keypair:
        name: "{{ local_ssh_key_name }}"
        public_key: "{{ _ssh_key_info.public_key }}"
        state: present

    - name: Apply terraform code to boot the servers
      community.general.terraform:
        project_path: "{{ local_terraform_project_path }}"
        force_init: true
        state: present
        variables:
          openmp_course_image: "{{ local_image | default(omit) }}"
          openmp_course_flavor: "{{ local_flavor | default(omit) }}"
          openmp_course_ssh_key_name: "{{ local_ssh_key_name | default(omit) }}"
          # https://github.com/ansible/ansible/issues/51687#issuecomment-520078406
          openmp_course_open_ports: "{{ local_open_ports | default(omit) | to_json }}"
          openmp_course_nodes_count: "{{ local_nodes_count | default(omit) }}"
          openmp_course_floating_ips_pool: "{{ local_floating_ips_pool | default(omit) }}"
          openmp_course_private_network: "{{ local_private_network | default(omit) }}"
      register: _terraform

    - name: Add servers to ansible in-memory inventory
      ansible.builtin.add_host:
        name: "openmp-course-0{{ ansible_loop.index }}"
        groups:
          - openmp_course
        ansible_host: "{{ item }}"
        ansible_user: "{{ local_ssh_remote_user }}"
        ansible_ssh_private_key_file: "{{ local_ssh_key_path }}"
      changed_when: false
      loop: "{{ _terraform.outputs.openmp_course_floating_ips.value }}"
      loop_control:
        extended: true

    - name: Create the ansible static inventory
      ansible.builtin.template:
        dest: "{{ playbook_dir }}/inventory/openmp_course"
        src: ansible_inventory_openmp_course.j2
        mode: 0644


- name: Wait for the machines to boot
  hosts: openmp_course
  become: no
  gather_facts: no
  remote_user: "{{ local_ssh_remote_user }}"

  tasks:

    - name: Waiting for the machines to be accessible over ssh
      ansible.builtin.wait_for_connection:
