---

- name: Delete the slurm cluster from the cloud
  hosts: localhost

  tasks:

    - pause:
        prompt: |

          PLEASE CONFIRM THAT YOU WANT TO DELETE THE SLURM CLUSTER
          Press return to continue. Press Ctrl+c and then "a" to abort

    - name: Delete login node
      os_server:
        name: "slurm-login"
        delete_fip: yes  # also delete the floating ip if exists
        wait: no
        state: absent

    - name: Delete dedicated NFS server
      os_server:
        name: "slurm-nfs-server"
        delete_fip: yes  # also delete the floating ip if exists
        wait: no
        state: absent

    - name: Delete dedicated slurm master
      os_server:
        name: "slurm-master"
        delete_fip: yes  # also delete the floating ip if exists
        wait: no
        state: absent

    - name: Query the names for all the compute nodes
      os_server_info:
        server: slurm-compute*
      register: _os_slurm_compute_info

    - name: Delete the slurm compute nodes (CAN TAKE SOME TIME!)
      os_server:
        name: "{{ item.name }}"
        delete_fip: yes  # also delete the floating ip if exists
        state: absent
        wait: no
      loop: "{{ _os_slurm_compute_info.openstack_servers }}"

    - name: Waiting for all the compute nodes to shutdown
      os_server_info:
        server: slurm-compute*
      register: _os_slurm_compute_info
      until: _os_slurm_compute_info.openstack_servers | length == 0
      retries: 40
      delay: 15

    - name: Delete cinder volume exported by nfs
      os_volume:
        display_name: "slurm_cluster_nfs_data"
        state: absent

    # - name: Delete default security group for the slurm cluster
    #   os_security_group:
    #     name: "{{ slurm_cluster_security_group_default }}"
    #     state: absent

    - name: Delete security group for the login node
      os_security_group:
        name: "{{ slurm_cluster_security_group_login }}"
        state: absent

    - name: Unregister ssh key from the cloud
      os_keypair:
        name: "{{ slurm_cluster_ssh_key_name }}"
        public_key_file: "{{ slurm_cluster_ssh_key_path }}.pub"
        state: absent
