---

- name: Configure the user accounts
  hosts:
    - slurm_master
    - slurm_compute
    - slurm_login
    - nfs_server
  gather_facts: true
  become: true
  remote_user: "{{ local_ssh_remote_user }}"

  tasks:

    - name: Create a default group "users" for every user
      ansible.builtin.group:
        name: "users"
        gid: 2000
        state: present

    # We do this in the NFS server to make sure that root can access the home folders (just in case root squash is enabled)
    - name: Create the user accounts (starting with uid 2001) | First in the NFS server to create home folders
      ansible.builtin.user:
        name: "user{{ item }}"
        uid: "20{{ item }}"
        group: "users"
        home: "{{ local_shared_folder }}/home/user{{ item }}"
        create_home: yes
        shell: /bin/bash
        update_password: always
        password: "{{ local_users_default_password }}"
        generate_ssh_key: yes
        ssh_key_comment: "user{{ item }}_slurm_cluster@ansible-generated"
        state: present
        ssh_key_file: .ssh/id_rsa
        ssh_key_type: rsa
      with_sequence: "count={{ local_users_accounts }} format=%02u"
      when: "'nfs_server' in group_names"

    - name: Create the user accounts (starting with uid 2001) | Now in every machine
      ansible.builtin.user:
        name: "user{{ item }}"
        uid: "20{{ item }}"
        group: "users"
        home: "{{ local_shared_folder }}/home/user{{ item }}"
        create_home: yes
        shell: /bin/bash
        update_password: always
        password: "{{ local_users_default_password }}"
        generate_ssh_key: yes
        ssh_key_comment: "user{{ item }}_slurm_cluster@ansible-generated"
        state: present
        ssh_key_file: .ssh/id_rsa
        ssh_key_type: rsa
      with_sequence: "count={{ local_users_accounts }} format=%02u"

    # We do this in the NFS server to make sure that root can access the home folders (just in case root squash is enabled)
    - name: Get the ssh public keys for every user
      ansible.builtin.slurp:
        src: "{{ local_shared_folder }}/home/user{{ item }}/.ssh/id_rsa.pub"
      register: _all_users_ssh_public_keys
      with_sequence: "count={{ local_users_accounts }} format=%02u"
      when: "'nfs_server' in group_names"

    # We do this in the NFS server to make sure that root can access the home folders (just in case root squash is enabled)
    - name: Add the user ssh keys to their accounts
      ansible.posix.authorized_key:
        user: "user{{ item.item }}"
        key: "{{ item.content | b64decode }}"
      loop: "{{ _all_users_ssh_public_keys.results }}"
      when: "'nfs_server' in group_names"

    # We do this in the NFS server to make sure that root can access the home folders (just in case root squash is enabled)
    - name: Deploy custom ssh config for each user
      ansible.builtin.blockinfile:
        path: "{{ local_shared_folder }}/home/user{{ item }}/.ssh/config"
        create: yes
        backup: yes
        owner: "user{{ item }}"
        mode: 0600
        marker: "# {mark} ANSIBLE MANAGED SSH CONFIG"
        block: |
          Host *
              StrictHostKeyChecking no
              ServerAliveInterval 10
      with_sequence: "count={{ local_users_accounts }} format=%02u"
      when: "'nfs_server' in group_names"

    - name: Add the teacher's ssh public keys to the centos account in login node
      ansible.posix.authorized_key:
        user: "centos"
        key: "{{ item }}"
      loop: "{{ local_teachers_ssh_keys }}"
      tags: ssh_keys_teachers

    - name: Create a private ssh key for user centos in login node
      ansible.builtin.user:
        name: "centos"
        generate_ssh_key: yes
        ssh_key_comment: "centos@slurm-login"
      when: "'slurm_login' in group_names"
      tags: ssh_keys_teachers

    - name: Fetch the centos user public ssh key from login node to ansible control host
      ansible.builtin.fetch:
        src: "~centos/.ssh/id_rsa.pub"
        dest: "/tmp/id_rsa_centos_login_node.pub"
        flat: yes
      when: "'slurm_login' in group_names"
      tags: ssh_keys_teachers

    - name: Add the public key for user centos to every machine
      ansible.builtin.authorized_key:
        user: "centos"
        key: "{{ lookup('file', '/tmp/id_rsa_centos_login_node.pub') }}"
      tags: ssh_keys_teachers

    - name: Configure a cgroups memory limit in login node for every user
      ansible.builtin.import_role:
        name: pescobar.cgroups_mem_limit
      vars:
        # this is the user group where all the users are created
        cgroup_to_whom_the_limit_applies: '@users'
      when: "'slurm_login' in group_names"
