---

- name: Configure slurm cluster (slurm master and slurm workers)
  hosts:
    - slurm_master
    - slurm_login
    - slurm_compute
  gather_facts: true
  become: true
  remote_user: "{{ local_ssh_remote_user }}"

  tasks:

    - name: Set vars for role scicore.slurm
      ansible.builtin.set_fact:
        slurm_master_host: "{{ groups['slurm_master'][0] }}"
        slurm_workers_group: slurm_compute  # this is the group name defined in the static inventory
        slurm_submit_group: slurm_login     # this is the group name defined in the static inventory

    - name: Deploy SLURM
      ansible.builtin.import_role:
        name: scicore.slurm
