---

- name: Common setup for every machine in the slurm cluster
  hosts: slurm_cluster_all
  gather_facts: true
  become: true

  tasks:

    - name: Configure NTP time
      ansible.builtin.import_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: "{{ slurm_ntp_timezone }}"

    - name: Add EPEL yum repo | RedHat
      ansible.builtin.package:
        name: epel-release
        state: installed
      when: ansible_os_family == 'RedHat'

    - name: Disable SElinux in RedHat systems
      ansible.builtin.import_role:
        name: pescobar.selinux_disable
      vars:
        selinux_disable_reboot: true
      when: ansible_os_family == 'RedHat'

    - name: Install some basic packages defined in variable 'slurm_packages_to_install'
      ansible.builtin.package:
        name: "{{ slurm_packages_to_install }}"

    - name: Deploy a custom /etc/hosts with all VMs in the tenant
      ansible.builtin.template:
        dest: /etc/hosts
        src: hosts_slurm.j2
        mode: 0644

    - name: Configure sshd to allow password authentication
      ansible.builtin.import_role:
        name: willshersystems.sshd
      vars:
        sshd:
          PasswordAuthentication: yes

    - name: Upgrade all the packages (if configured)
      ansible.builtin.yum:
        name: '*'
        state: latest
      when:
        - slurm_upgrade_all_packages
        - ansible_os_family == 'RedHat'
